#!/usr/bin/env node
// Generates sw-assets.js, the service worker's precache list (DESIGN §2.6):
//   self.ASSETS = [...]; self.INTEGRITY = {path: base64 sha256}; self.ASSET_VERSION = '<12 hex>'
// ASSETS = every file scripts/stage-web.mjs stages (the desktop app's files), minus the service worker scripts
// themselves (the browser update-checks importScripts'd files on its own). ASSET_VERSION is derived from the
// list and the hashes, so the cache name changes whenever any precached byte changes.
//
//   node scripts/precache.mjs          (re)write sw-assets.js
//   node scripts/precache.mjs --check  exit 1 when sw-assets.js is stale (CI)
import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { ROOT, listStagedFiles } from './stage-web.mjs';

export const OUT = path.join(ROOT, 'sw-assets.js');
/** Never precached: the worker and the scripts it imports. */
export const EXCLUDE = Object.freeze(['sw.js', 'sw-assets.js', 'sw-stream.js']);

/**
 * @param {string} [root]
 * @returns {{assets: string[], integrity: Record<string, string>, version: string}}
 */
export function computeAssets(root = ROOT) {
  const assets = listStagedFiles(root).filter((f) => !EXCLUDE.includes(f));
  const integrity = {};
  const all = createHash('sha256');
  for (const rel of assets) {
    const digest = createHash('sha256').update(readFileSync(path.join(root, rel))).digest('base64');
    integrity[rel] = digest;
    all.update(`${rel}\0${digest}\n`);
  }
  return { assets, integrity, version: all.digest('hex').slice(0, 12) };
}

/**
 * The exact text of sw-assets.js for a computed asset set.
 * @param {{assets: string[], integrity: Record<string, string>, version: string}} a
 * @returns {string}
 */
export function render({ assets, integrity, version }) {
  const lines = [
    '// GENERATED by scripts/precache.mjs — do not edit. Regenerate: node scripts/precache.mjs',
    `self.ASSETS = ${JSON.stringify(assets, null, 2)};`,
    `self.INTEGRITY = ${JSON.stringify(integrity, null, 2)};`,
    `self.ASSET_VERSION = '${version}';`,
    '',
  ];
  return lines.join('\n');
}

/**
 * @param {{root?: string, out?: string, check?: boolean}} [opts]
 * @returns {{stale: boolean, version: string, count: number}}
 */
export function run({ root = ROOT, out = OUT, check = false } = {}) {
  const computed = computeAssets(root);
  const text = render(computed);
  const current = existsSync(out) ? readFileSync(out, 'utf8') : null;
  const stale = current !== text;
  if (!check && stale) writeFileSync(out, text);
  return { stale, version: computed.version, count: computed.assets.length };
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;
if (isMain) {
  const check = process.argv.includes('--check');
  const { stale, version, count } = run({ check });
  if (check) {
    if (stale) {
      console.error('[precache] sw-assets.js is stale: run `node scripts/precache.mjs` and commit the result.');
      process.exit(1);
    }
    console.log(`[precache] sw-assets.js is up to date (${count} assets, version ${version}).`);
  } else {
    console.log(`[precache] ${stale ? 'wrote' : 'unchanged'} sw-assets.js (${count} assets, version ${version}).`);
  }
}
